# Exception Handling

def fun():
    try :
        return 100/x
    except:
        return "there is a zero division error"
    ans = fun(0)
    print(ans)
